---
title: "Teaching"
---


## Workshop facilitation


  - Facilitator for student workshops held by the Graduates’ Association for Political Science, Western University:
    - “Writing Loops and Functions in R,” 17 February 2023.
    - “Intro to R,” 29-30 August 2022.
    - “R:ggplot Tips and Tricks,” 7 April 2021.
- Facilitator for student workshops held by the Political Science Graduate Students’ Association, University of Calgary:
    - “Data Visualization in Excel,” 4 April 2018.
    - “Intermediate SPSS: Coding and Workflow,” 22 November 2018.
    - “Intermediate SPSS: Coding and Workflow,” 14 March 2018.
    - “Data Visualization in Excel,” 27 November 2017.
    - “Coding in SPSS,” 22 April 2017.

- Co-facilitator at Workshops on Social Science (WSSR), Concordia University:
    - “Public Opinion and Polling: Is Western Alienation for Real?” Workshop co-facilitated with Janet Brown and the Workshops on Social Science (WSSR) at Concordia University, Montreal, 14 February 2020.
    - “Public Opinion and Polling: Understanding Alberta’s Political Culture.” Workshop co-facilitated with Janet Brown and the Workshops on Social Science (WSSR) at Concordia University, Montreal, 1 February 2019.


## Guest lectures


  - “RDD and online panel sampling in market research,” STAT423 (Statistical Analysis of Survey Data) for Jim Stallard, University of Calgary, 12 March 2021.
  - “A (former) pollster’s perspective on survey research,” CRIM2303A (Research Methods) for Carolyn Gordon, University of Ottawa, 17 November, 2020.
  - “Focus groups,” POST 2208 (Qualitative Research Methods) for Duane Bratt, Mount Royal University, 10 February 2020.
  - “A pollster’s perspective on political research,” POLI 429 (Electoral Behaviour) for Melanee Thomas, University of Calgary, 23 February 2020.
  - “Focus groups,” POST 2208 (Qualitative Research Methods) for Duane Bratt, Mount Royal University, 3 December 2018.
  - “Legislatures,” POLI 321 (Intro to Canadian Politics) for Anthony Sayers, May 29, 2018.
  - “Applying what you learn in POLI 399 beyond the classroom (or, how to get a job with a political science degree),” POLI 399 (Quantitative Research Methods) for Melanee Thomas, University of Calgary, 6 March 2018.
  - “What structures political attitudes when ideology doesn’t?” POLI 429 (Electoral Behaviour) for Melanee Thomas, University of Calgary, 6 March 2018
  - “Statist versus cosmopolitan responses to terrorism,” POLI 439 (Strategic Studies) for Rob Huebert, University of Calgary, 3 March 2018.
  
  
## Teaching assistant experience


  - PS 9591B (Quantitative Methods II: Regression and Causal Inference) for Mathieu Turgeon, Western University, Winter 2023
  - PS 2545G (Comparative Politics) for Bruce Morrison, Western University, Winter 2022.
  - POLI 439 (Strategic Studies) for Rob Huebert, University of Calgary, Winter 2018.
  - POLI 399 (Quantitative Research Methods) for Kim-Lee Tuxhorn, University of Calgary, Fall 2017.
  - POLI 399 (Quantitative Research Methods) for Brenda O’Neill, University of Calgary, Winter 2017.
  - POLI 399 (Quantitative Research Methods) for Melanee Thomas, University of Calgary, Fall 2016.

